<?xml version="1.0" encoding="utf-8"?><Database Name="Petra5" Class="MicrogenDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.cclv_AllEntities" Member="cclv_AllEntities">
    <Type Name="cclv_AllEntity">
      <Column Name="EntityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntityKey" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RegistrationNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EntityTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntityTypeDesc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EntitySubTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EntitySubTypeDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusDesc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StatusCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StatusCategoryDesc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SecurityUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamDesc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ManagingEntityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>