#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petratracker.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Petra5")]
	public partial class MicrogenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MicrogenDataContext() : 
				base("Data Source=ELMINA\\SQLEXPRESS;Initial Catalog=Petra5;Integrated Security=True", mappingSource)
		{
			OnCreated();
		}
		
		public MicrogenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MicrogenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MicrogenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MicrogenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cclv_AllEntity> cclv_AllEntities
		{
			get
			{
				return this.GetTable<cclv_AllEntity>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cclv_AllEntities")]
	public partial class cclv_AllEntity
	{
		
		private int _EntityID;
		
		private string _EntityKey;
		
		private string _FullName;
		
		private string _RegistrationNumber;
		
		private string _ShortName;
		
		private int _EntityTypeID;
		
		private string _EntityTypeDesc;
		
		private System.Nullable<int> _EntitySubTypeID;
		
		private string _EntitySubTypeDesc;
		
		private int _StatusID;
		
		private string _StatusDesc;
		
		private int _StatusCategoryID;
		
		private string _StatusCategoryDesc;
		
		private System.Nullable<int> _SecurityUserID;
		
		private System.Nullable<int> _TeamID;
		
		private string _TeamDesc;
		
		private string _Description;
		
		private System.Nullable<int> _ManagingEntityID;
		
		public cclv_AllEntity()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityID", DbType="Int NOT NULL")]
		public int EntityID
		{
			get
			{
				return this._EntityID;
			}
			set
			{
				if ((this._EntityID != value))
				{
					this._EntityID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityKey", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string EntityKey
		{
			get
			{
				return this._EntityKey;
			}
			set
			{
				if ((this._EntityKey != value))
				{
					this._EntityKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(255)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationNumber", DbType="VarChar(20)")]
		public string RegistrationNumber
		{
			get
			{
				return this._RegistrationNumber;
			}
			set
			{
				if ((this._RegistrationNumber != value))
				{
					this._RegistrationNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="NVarChar(255)")]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this._ShortName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityTypeID", DbType="Int NOT NULL")]
		public int EntityTypeID
		{
			get
			{
				return this._EntityTypeID;
			}
			set
			{
				if ((this._EntityTypeID != value))
				{
					this._EntityTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntityTypeDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EntityTypeDesc
		{
			get
			{
				return this._EntityTypeDesc;
			}
			set
			{
				if ((this._EntityTypeDesc != value))
				{
					this._EntityTypeDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntitySubTypeID", DbType="Int")]
		public System.Nullable<int> EntitySubTypeID
		{
			get
			{
				return this._EntitySubTypeID;
			}
			set
			{
				if ((this._EntitySubTypeID != value))
				{
					this._EntitySubTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntitySubTypeDesc", DbType="NVarChar(50)")]
		public string EntitySubTypeDesc
		{
			get
			{
				return this._EntitySubTypeDesc;
			}
			set
			{
				if ((this._EntitySubTypeDesc != value))
				{
					this._EntitySubTypeDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int NOT NULL")]
		public int StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StatusDesc
		{
			get
			{
				return this._StatusDesc;
			}
			set
			{
				if ((this._StatusDesc != value))
				{
					this._StatusDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusCategoryID", DbType="Int NOT NULL")]
		public int StatusCategoryID
		{
			get
			{
				return this._StatusCategoryID;
			}
			set
			{
				if ((this._StatusCategoryID != value))
				{
					this._StatusCategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusCategoryDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StatusCategoryDesc
		{
			get
			{
				return this._StatusCategoryDesc;
			}
			set
			{
				if ((this._StatusCategoryDesc != value))
				{
					this._StatusCategoryDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityUserID", DbType="Int")]
		public System.Nullable<int> SecurityUserID
		{
			get
			{
				return this._SecurityUserID;
			}
			set
			{
				if ((this._SecurityUserID != value))
				{
					this._SecurityUserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int")]
		public System.Nullable<int> TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					this._TeamID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TeamDesc
		{
			get
			{
				return this._TeamDesc;
			}
			set
			{
				if ((this._TeamDesc != value))
				{
					this._TeamDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagingEntityID", DbType="Int")]
		public System.Nullable<int> ManagingEntityID
		{
			get
			{
				return this._ManagingEntityID;
			}
			set
			{
				if ((this._ManagingEntityID != value))
				{
					this._ManagingEntityID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
